name: Build code-server image
run-name: Build(code-server) ${{ github.ref_name }}

on:
  workflow_dispatch:

  pull_request:
    branches:
      - 'main'

  schedule:
    - cron: "30 17 * * *"

permissions:
  contents: read
  packages: write

env:
  PUB_IMAGE: archie2016/code-server
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/code-server
  ACR_IMAGE: ${{ secrets.ACR_MY_REGISTY }}/osc-org/code-server
  QCR_IMAGE: ${{ secrets.QCR_REGISTRY }}/osc-org/code-server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6


      # ------------------------------------------------
      # 获取最新 upstream version-* tag
      # ------------------------------------------------
      - name: Resolve upstream image version
        shell: bash
        run: |
          set -euo pipefail

          BASE_VERSION=$(
            skopeo list-tags docker://docker.io/linuxserver/code-server \
              | jq -r '.Tags[]' \
              | grep '^version-[0-9]' \
              | sort -V \
              | tail -n1
          )

          if [[ -z "${BASE_VERSION}" ]]; then
            echo "Failed to resolve upstream version"
            exit 1
          fi

          echo "BASE_VERSION=${BASE_VERSION}" >> $GITHUB_ENV

          echo "Upstream version: ${BASE_VERSION}"

      - name: Resolve image version
        shell: bash
        run: |
          set -euo pipefail
          VERSION=${BASE_VERSION#version-}

          echo "VERSION=${VERSION}" >> $GITHUB_ENV

          echo "Image version: ${VERSION}"

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          username: archie2016
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 登录 GitHub Container Registry
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      # 登录 ACR Container Registry
      - name: Login to ACR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          registry: ${{ secrets.ACR_REGISTY }}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASS }}

      - name: Log in to QCR Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.QCR_REGISTRY }}
          username: ${{ secrets.QCR_USER }}
          password: ${{ secrets.QCR_PASS }}

      # ------------------------------------------------
      # Buildx
      # ------------------------------------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      # =========================
      # build
      # =========================
      - name: Build and Push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.PUB_IMAGE }}:${{ env.VERSION }}
            ${{ env.PUB_IMAGE }}:latest
          build-args: |
            BASE_VERSION=${{ env.BASE_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
